### PR TITLE
Add basic introduction to portfolio website

### PR DESCRIPTION
**Pull request by queden**

### CODE REVIEW

**Comment by ArunChauhan** [comment]
LGTM.

**Comment by ArunChauhan** [comment]
Sorry, I closed your pull request by mistake.

**Comment by queden** [comment]
I think it only needed Chun-Yu to approve, as it allowed me to merge. Is there a setting I would need to change to require approval from both of you?

**Comment by ArunChauhan** [comment]
It's fine, you don't need to require multiple reviews for a simple branch like this. But, you can use this in the future.

https://github.blog/2018-03-23-require-multiple-reviewers/

**Comment by queden** [comment]
Okay makes sense, thank you!

**Pull request merged**
