### PR TITLE
Final styling

### PR DESCRIPTION
**Pull request by queden**
I configured the site for build, and I updated the styling for the site. I also updated the Google logo used to meet the Brand Permissions guidelines.

### CODE REVIEW

**Comment by queden** [comment]
Good point. I will .gitignore the webapp folder and then update the README. Thank you!

**Comment by cshei** [comment]
Great!  But since your previous commit adding all those files is still in this pull request, I think they will still get added (and removed, but they'll still live in the .git directory somewhere) to your git repo.  I'm not sure which is easier, but I'd suggest either finding a way to rebase/squash the add/remove commits into a single commit (so they never get added) or start a new branch and pull request that omits them from the beginning.

**Comment by queden** [comment]
I think the original commit to add all of those files is early on (therefore the files persist up until the last change I just made to ignore them). Would it be too much to just squash all of the commits together into one?

**Comment by ArunChauhan** [comment]
> I think the original commit to add all of those files is early on (therefore the files persist up until the last change I just made to ignore them). Would it be too much to just squash all of the commits together into one?

I think it's fine to squash the commits because, fortunately, the commits have been small so far.

**Comment by queden** [comment]
Okay great! I believe there is an option to squash all commits and merge that appears once the PR is approved. Can I do that, or should I do it manually first?

**Comment by ArunChauhan** [comment]
Quick question: about how many files will you have added for Angular at the end of this?  I don't need an exact count, just an order of the number (~10 or ~100 or ~1000?).

**Comment by queden** [comment]
If I am not mistaken, it should only be in the ~10 order of magnitude

**Pull request merged**
